// Integration test for the per-board "out-of-box demo" Stage fixtures
// generated by `tool/generate_board_demo_fixtures.dart`.
//
// For every Open Core board widget there are two fixtures:
//
//   <board>_demo_per_bit.vcd — individual 1-bit slot signals. Asserts
//       the per-bit / exact-match auto-bind tier lands every LED,
//       switch, button, and seven-segment slot.
//   <board>_demo_vector.vcd  — packed `leds` / `sws` (and `btn` / `key`)
//       buses. Asserts the vector-fan-out auto-bind tier lands the LED
//       and switch rows from a single dropped bus.
//
// Both files are driven by the same animation, so binding either one
// brings the same board to life — this test only checks that the
// signals parse and auto-bind as intended; the visual behaviour is
// covered by the manual verification guide.

import 'package:flutter_test/flutter_test.dart';
import 'package:wavecrux/domain/enums/stage_widget_category.dart';
import 'package:wavecrux/domain/interfaces/compound_stage_widget.dart';
import 'package:wavecrux/domain/models/board_auto_bind_candidate.dart';
import 'package:wavecrux/domain/models/signal_filter.dart';
import 'package:wavecrux/domain/models/variable.dart';
import 'package:wavecrux/features/stage/widgets/boards/arty_a7_stage_widget.dart';
import 'package:wavecrux/features/stage/widgets/boards/basys3_stage_widget.dart';
import 'package:wavecrux/features/stage/widgets/boards/de10_lite_stage_widget.dart';
import 'package:wavecrux/features/stage/widgets/boards/nexys_a7_stage_widget.dart';
import 'package:wavecrux/services/stage/board_auto_bind_service.dart';
import 'package:wavecrux/services/waveform/wellen_provider.dart';

class _BoardCase {
  const _BoardCase({
    required this.id,
    required this.compound,
    required this.ledPrefix,
    required this.ledCount,
    required this.switchCount,
    required this.buttonNames,
    this.digitPrefix,
    this.digitCount = 0,
  });

  final String id;
  final CompoundStageWidget compound;
  final String ledPrefix;
  final int ledCount;
  final int switchCount;
  final List<String> buttonNames;
  final String? digitPrefix;
  final int digitCount;

  String get dir => 'test/fixtures/stage/boards/$id';
  String get perBit => '$dir/${id}_demo_per_bit.vcd';
  String get vector => '$dir/${id}_demo_vector.vcd';
}

const _cases = [
  _BoardCase(
    id: 'basys3',
    compound: Basys3StageWidget(),
    ledPrefix: 'led',
    ledCount: 16,
    switchCount: 16,
    buttonNames: ['btnC', 'btnU', 'btnL', 'btnR', 'btnD'],
    digitPrefix: 'digit',
    digitCount: 4,
  ),
  _BoardCase(
    id: 'nexys_a7',
    compound: NexysA7StageWidget(),
    ledPrefix: 'led',
    ledCount: 16,
    switchCount: 16,
    buttonNames: ['btnC', 'btnU', 'btnL', 'btnR', 'btnD'],
    digitPrefix: 'digit',
    digitCount: 8,
  ),
  _BoardCase(
    id: 'de10_lite',
    compound: De10LiteStageWidget(),
    ledPrefix: 'ledr',
    ledCount: 10,
    switchCount: 10,
    buttonNames: ['key0', 'key1'],
    digitPrefix: 'hex',
    digitCount: 6,
  ),
  _BoardCase(
    id: 'arty_a7',
    compound: ArtyA7StageWidget(),
    ledPrefix: 'led',
    ledCount: 8,
    switchCount: 4,
    buttonNames: ['btn0', 'btn1', 'btn2', 'btn3'],
  ),
];

Map<String, Variable> _byPath(WellenProvider provider) {
  final vars = provider.findVariables(const SignalFilter());
  return {for (final v in vars) v.fullPath: v};
}

void main() {
  const service = BoardAutoBindService();

  // Every board widget is a Board-category compound — sanity guard so a
  // future refactor doesn't silently re-point a case at a non-board.
  test('all demo-fixture board widgets are board-category compounds', () {
    for (final c in _cases) {
      expect(c.compound.category, StageWidgetCategory.board, reason: c.id);
    }
  });

  for (final c in _cases) {
    group('${c.id} demo fixtures', () {
      group('per-bit', () {
        late WellenProvider provider;
        setUp(() async {
          provider = WellenProvider();
          await provider.openFile(c.perBit);
        });
        tearDown(() => provider.close());

        test('exposes every per-bit slot signal', () {
          final paths = _byPath(provider).keys.toSet();
          for (var i = 0; i < c.ledCount; i++) {
            expect(paths, contains('top.${c.ledPrefix}$i'));
          }
          for (var i = 0; i < c.switchCount; i++) {
            expect(paths, contains('top.sw$i'));
          }
          for (final name in c.buttonNames) {
            expect(paths, contains('top.$name'));
          }
          for (var i = 0; i < c.digitCount; i++) {
            expect(paths, contains('top.${c.digitPrefix}$i'));
          }
        });

        test('auto-bind lands LED/switch/button/digit slots', () {
          final result = service.computeBindings(
            slots: c.compound.slots,
            availableSignals: _byPath(provider),
          );
          for (var i = 0; i < c.ledCount; i++) {
            final slot = '${c.ledPrefix}$i';
            expect(
              result.candidates[slot]?.confidence,
              BoardAutoBindConfidence.exactMatch,
              reason: '$slot per-bit match',
            );
          }
          for (var i = 0; i < c.switchCount; i++) {
            expect(
              result.candidates['sw$i']?.confidence,
              BoardAutoBindConfidence.exactMatch,
            );
          }
          for (final name in c.buttonNames) {
            expect(
              result.candidates[name]?.confidence,
              BoardAutoBindConfidence.exactMatch,
              reason: 'button $name',
            );
          }
          for (var i = 0; i < c.digitCount; i++) {
            final slot = '${c.digitPrefix}$i';
            expect(
              result.candidates[slot]?.confidence,
              isNot(BoardAutoBindConfidence.noMatch),
              reason: '$slot should bind',
            );
          }
        });
      });

      group('vector', () {
        late WellenProvider provider;
        setUp(() async {
          provider = WellenProvider();
          await provider.openFile(c.vector);
        });
        tearDown(() => provider.close());

        test('exposes packed leds/sws buses of the right width', () {
          final byPath = _byPath(provider);
          expect(byPath['top.leds']?.bitWidth, c.ledCount);
          expect(byPath['top.sws']?.bitWidth, c.switchCount);
        });

        test('LED/switch rows fan out from the packed buses', () {
          final result = service.computeBindings(
            slots: c.compound.slots,
            availableSignals: _byPath(provider),
          );
          for (var i = 0; i < c.ledCount; i++) {
            final slot = '${c.ledPrefix}$i';
            expect(
              result.candidates[slot]?.confidence,
              BoardAutoBindConfidence.vectorFanOut,
              reason: '$slot fan-out',
            );
          }
          for (var i = 0; i < c.switchCount; i++) {
            expect(
              result.candidates['sw$i']?.confidence,
              BoardAutoBindConfidence.vectorFanOut,
            );
          }
          for (var i = 0; i < c.digitCount; i++) {
            final slot = '${c.digitPrefix}$i';
            expect(
              result.candidates[slot]?.confidence,
              isNot(BoardAutoBindConfidence.noMatch),
            );
          }
        });
      });
    });
  }
}
