// Integration test for the per-board "out-of-box demo" Pro Stage
// fixtures generated by `tool/generate_board_demo_fixtures.dart`.
//
// For every Pro-pack board widget there are two fixtures:
//
//   <board>_demo_per_bit.vcd — individual 1-bit slot signals. Asserts
//       the per-bit / exact-match auto-bind tier lands every LED,
//       switch, and button slot.
//   <board>_demo_vector.vcd  — packed `leds` / `sws` (and `btn` / `key`)
//       buses. Asserts the vector-fan-out tier lands the LED and switch
//       rows from a single dropped bus.
//
// Both files additionally carry the board's peripheral signals (HDMI
// framebuffer pins, audio codec, ADC channels, accelerometer, OLED),
// named to match the board's peripheral slots so the auto-bind service
// wires them up. This test checks parsing + auto-bind; the visual
// behaviour is covered by the manual verification guide.

import 'package:flutter_test/flutter_test.dart';
import 'package:wavecrux/domain/interfaces/compound_stage_widget.dart';
import 'package:wavecrux/domain/models/board_auto_bind_candidate.dart';
import 'package:wavecrux/domain/models/signal_filter.dart';
import 'package:wavecrux/domain/models/variable.dart';
import 'package:wavecrux/services/stage/board_auto_bind_service.dart';
import 'package:wavecrux/services/waveform/wellen_provider.dart';
import 'package:wavecrux_pro/features/stage_pro/widgets/boards/de10_nano_stage_widget.dart';
import 'package:wavecrux_pro/features/stage_pro/widgets/boards/hdmi_slot_builder.dart';
import 'package:wavecrux_pro/features/stage_pro/widgets/boards/nexys_video_stage_widget.dart';
import 'package:wavecrux_pro/features/stage_pro/widgets/boards/zybo_z7_stage_widget.dart';

class _BoardCase {
  const _BoardCase({
    required this.id,
    required this.compound,
    required this.ledCount,
    required this.switchCount,
    required this.buttonNames,
    required this.peripheralSlots,
  });

  final String id;
  final CompoundStageWidget compound;
  final int ledCount;
  final int switchCount;
  final List<String> buttonNames;

  /// Peripheral slot names that must auto-bind (they carry matching
  /// signals in both fixtures).
  final List<String> peripheralSlots;

  String get dir => 'test/fixtures/stage_pro/boards/$id';
  String get perBit => '$dir/${id}_demo_per_bit.vcd';
  String get vector => '$dir/${id}_demo_vector.vcd';
}

List<String> _hdmiChips(String prefix) {
  final n = hdmiSiblingSlotNames(prefix);
  return [n.data, n.pixelClk, n.hSync, n.vSync, n.dataEnable];
}

final _cases = <_BoardCase>[
  _BoardCase(
    id: 'de10_nano',
    compound: const De10NanoStageWidget(),
    ledCount: De10NanoStageWidget.ledCount,
    switchCount: De10NanoStageWidget.switchCount,
    buttonNames: De10NanoStageWidget.buttonNames,
    peripheralSlots: [
      ..._hdmiChips(De10NanoStageWidget.hdmiOutSlotName),
      De10NanoStageWidget.accelSlotName,
      for (var i = 0; i < De10NanoStageWidget.adcChannelCount; i++) 'adc_ch$i',
    ],
  ),
  _BoardCase(
    id: 'nexys_video',
    compound: const NexysVideoStageWidget(),
    ledCount: NexysVideoStageWidget.ledCount,
    switchCount: NexysVideoStageWidget.switchCount,
    buttonNames: NexysVideoStageWidget.buttonNames,
    peripheralSlots: [
      ..._hdmiChips(NexysVideoStageWidget.hdmiInSlotName),
      ..._hdmiChips(NexysVideoStageWidget.hdmiOutSlotName),
      NexysVideoStageWidget.oledSlotName,
      NexysVideoStageWidget.audioCodecSlotName,
    ],
  ),
  _BoardCase(
    id: 'zybo_z7',
    compound: const ZyboZ7StageWidget(),
    ledCount: ZyboZ7StageWidget.ledCount,
    switchCount: ZyboZ7StageWidget.switchCount,
    buttonNames: const ['btn0', 'btn1', 'btn2', 'btn3'],
    peripheralSlots: [
      ..._hdmiChips(ZyboZ7StageWidget.hdmiInSlotName),
      ..._hdmiChips(ZyboZ7StageWidget.hdmiOutSlotName),
      ZyboZ7StageWidget.audioMicInSlotName,
      ZyboZ7StageWidget.audioHeadphoneOutSlotName,
      ...ZyboZ7StageWidget.rgbLedSlotNames,
    ],
  ),
];

Map<String, Variable> _byPath(WellenProvider provider) {
  final vars = provider.findVariables(const SignalFilter());
  return {for (final v in vars) v.fullPath: v};
}

void _expectBound(BoardAutoBindResult result, String slot) {
  expect(result.candidates[slot]?.confidence,
      isNot(BoardAutoBindConfidence.noMatch),
      reason: '$slot should auto-bind');
}

void main() {
  const service = BoardAutoBindService();

  for (final c in _cases) {
    group('${c.id} demo fixtures', () {
      group('per-bit', () {
        late WellenProvider provider;
        setUp(() async {
          provider = WellenProvider();
          await provider.openFile(c.perBit);
        });
        tearDown(() => provider.close());

        test('exposes every per-bit LED/switch/button signal', () {
          final paths = _byPath(provider).keys.toSet();
          for (var i = 0; i < c.ledCount; i++) {
            expect(paths, contains('top.led$i'));
          }
          for (var i = 0; i < c.switchCount; i++) {
            expect(paths, contains('top.sw$i'));
          }
          for (final name in c.buttonNames) {
            expect(paths, contains('top.$name'));
          }
        });

        test('auto-bind lands LEDs, switches, buttons, and peripherals', () {
          final result = service.computeBindings(
            slots: c.compound.slots,
            availableSignals: _byPath(provider),
          );
          for (var i = 0; i < c.ledCount; i++) {
            expect(result.candidates['led$i']?.confidence,
                BoardAutoBindConfidence.exactMatch);
          }
          for (var i = 0; i < c.switchCount; i++) {
            expect(result.candidates['sw$i']?.confidence,
                BoardAutoBindConfidence.exactMatch);
          }
          for (final name in c.buttonNames) {
            _expectBound(result, name);
          }
          for (final slot in c.peripheralSlots) {
            _expectBound(result, slot);
          }
        });
      });

      group('vector', () {
        late WellenProvider provider;
        setUp(() async {
          provider = WellenProvider();
          await provider.openFile(c.vector);
        });
        tearDown(() => provider.close());

        test('exposes packed leds/sws buses of the right width', () {
          final byPath = _byPath(provider);
          expect(byPath['top.leds']?.bitWidth, c.ledCount);
          expect(byPath['top.sws']?.bitWidth, c.switchCount);
        });

        test('LED/switch rows fan out; peripherals still bind', () {
          final result = service.computeBindings(
            slots: c.compound.slots,
            availableSignals: _byPath(provider),
          );
          for (var i = 0; i < c.ledCount; i++) {
            expect(result.candidates['led$i']?.confidence,
                BoardAutoBindConfidence.vectorFanOut);
          }
          for (var i = 0; i < c.switchCount; i++) {
            expect(result.candidates['sw$i']?.confidence,
                BoardAutoBindConfidence.vectorFanOut);
          }
          for (final slot in c.peripheralSlots) {
            _expectBound(result, slot);
          }
        });
      });
    });
  }
}
